# Generated by Django 5.0.1 on 2024-10-20 12:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0009_alter_sub_category_options'),
        ('origin', '0002_origin_district'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(upload_to='images/product/prd')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='images/product/prd')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='images/product/prd')),
                ('stock_quantity', models.IntegerField()),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=10)),
                ('discount', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('status', models.CharField(choices=[('Out of stock', 'Out of stock'), ('Sale', 'Sale'), ('Upcomming', 'Upcomming'), ('Not available', 'Not available'), ('Deals of the day', 'Deals of the day'), ('Trending', 'Trending')], default='Sale', max_length=20)),
                ('mfg_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('exp_date', models.DateField(blank=True, null=True)),
                ('sold_quantity', models.PositiveIntegerField(default=0, null=True)),
                ('total_review', models.IntegerField(default=0, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, null=True)),
                ('delevery_massage', models.TextField(default='Delevery need to 2 hour for local items, 7 working days for thus items thats deleverd from outside of you city', null=True)),
                ('local_delevery', models.BooleanField(default=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.product_category')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.origin')),
                ('review', models.ManyToManyField(blank=True, null=True, to='review.review')),
            ],
            options={
                'ordering': ['sub_category'],
            },
        ),
    ]
