# Generated by Django 5.0.1 on 2024-05-06 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('total_review', models.IntegerField(default=0, null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(upload_to='images/product/prd')),
                ('stock_quantity', models.IntegerField()),
                ('sold_quantity', models.IntegerField(default=0, null=True)),
                ('description', models.TextField()),
                ('size_or_weight', models.CharField(max_length=5)),
                ('mfg_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.product_category')),
            ],
        ),
    ]
