# Generated by Django 5.0.1 on 2024-07-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
