# Generated by Django 5.0.1 on 2024-07-11 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
        ('product', '0004_product_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo1',
            field=models.ImageField(null=True, upload_to='images/product/prd'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo2',
            field=models.ImageField(null=True, upload_to='images/product/prd'),
        ),
    ]
