# Generated by Django 5.0.1 on 2024-07-11 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
        ('product', '0005_product_brand_product_photo1_product_photo2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.origin'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/prd'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/prd'),
        ),
    ]
