# Generated by Django 5.0.1 on 2024-07-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Out of stock', 'Out of stock'), ('Sale', 'Sale'), ('Upcomming', 'Upcomming'), ('Not available', 'Not available'), ('Deals of the day', 'Deals of the day'), ('Trending', 'Trending')], default='Sale', max_length=20),
        ),
    ]
