# Generated by Django 5.0.1 on 2024-07-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_product_category_name'),
        ('product', '0011_alter_product_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('category', 'sub_category')},
        ),
    ]
