# Generated by Django 5.0.1 on 2024-08-08 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mfg_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
