# Generated by Django 5.0.1 on 2024-08-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_delevery_massage_product_local_delevery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delevery_massage',
            field=models.TextField(default='Delevery need to 2 hour for local items, 7 working days for thus items thats deleverd from outside of you city', null=True),
        ),
    ]
