# Generated by Django 5.0.1 on 2024-11-04 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('origin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(upload_to='images/seller/')),
                ('mobile', models.CharField(max_length=12)),
                ('product_sell', models.IntegerField(default=0, null=True)),
                ('sell_amount', models.IntegerField(default=0, null=True)),
                ('total_review', models.IntegerField(default=0, null=0)),
                ('review_count', models.IntegerField(default=0, null=True)),
                ('Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
