# Generated by Django 5.0.1 on 2024-07-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='store_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
