# Generated by Django 5.0.1 on 2024-11-26 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller',
            old_name='Location',
            new_name='location',
        ),
    ]
