# Generated by Django 5.0.1 on 2024-11-26 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_remove_location_latitude_remove_location_longitude'),
        ('seller', '0002_rename_location_seller_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.location'),
        ),
    ]
