# Generated by Django 5.0.1 on 2024-07-13 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0002_origin_district'),
        ('seller', '0002_alter_seller_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.origin'),
        ),
    ]
