# Generated by Django 5.0.1 on 2024-12-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_seller_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/seller/'),
        ),
    ]
