# Generated by Django 5.0.1 on 2024-08-14 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coustomer_mobile_num'),
        ('seller', '0004_remove_seller_total_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='coustomer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.coustomer'),
        ),
    ]
