# Generated by Django 5.0.1 on 2024-07-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0002_product_category_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('postal', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(default='Bangladesh', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='images/brand/')),
                ('contact_num', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('total_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('product_type', models.ManyToManyField(to='category.product_category')),
            ],
        ),
    ]
