# Generated by Django 5.0.1 on 2024-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='origin',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
