# Generated by Django 5.0.1 on 2024-10-20 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('origin', '0003_location'),
        ('product', '0003_remove_product_local_delevery_remove_product_origin_and_more'),
        ('seller', '0002_remove_seller_origin_remove_seller_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
