# Generated by Django 5.0.1 on 2024-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('origin', '0002_origin_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='address',
            field=models.ManyToManyField(to='origin.origin'),
        ),
    ]
