# Generated by Django 5.0.1 on 2024-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=10, null=True),
        ),
    ]
