# Generated by Django 5.0.1 on 2024-08-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coustomer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='mobile_num',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
