# Generated by Django 5.0.1 on 2024-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_coustomer_mobile_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='coustomer',
            name='photo',
            field=models.ImageField(null=True, upload_to='image/coustomer/'),
        ),
    ]
