# Generated by Django 5.0.1 on 2024-08-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coustomer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coustomer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='image/coustomer/'),
        ),
    ]
