# Generated by Django 5.0.1 on 2024-11-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_coustomer_location'),
        ('origin', '0002_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coustomer',
            name='address',
        ),
        migrations.AddField(
            model_name='coustomer',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='origin.location'),
        ),
    ]
