# Generated by Django 5.0.1 on 2024-11-26 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_coustomer_address_coustomer_address'),
        ('origin', '0002_remove_location_latitude_remove_location_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coustomer',
            name='address',
        ),
        migrations.AddField(
            model_name='coustomer',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='origin.location'),
        ),
    ]
