# Generated by Django 5.0.1 on 2024-07-15 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_product_category_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='images/category/sub_cat/')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.product_category')),
            ],
        ),
    ]
