# Generated by Django 5.0.1 on 2024-07-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='image',
            field=models.ImageField(null=True, upload_to='images/category/sub_cat/'),
        ),
    ]
