# Generated by Django 5.0.1 on 2024-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_sub_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
