# Generated by Django 5.0.1 on 2024-07-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_alter_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='parent_category',
        ),
    ]
