# Generated by Django 5.0.1 on 2024-07-23 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_product_category_parent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.product_category'),
        ),
    ]
