# Generated by Django 5.0.1 on 2024-08-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_product_category_parent_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_category',
            options={'ordering': ['name']},
        ),
    ]
